# Generated by Django 6.0.2 on 2026-09-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_seo_description_product_seo_title'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Необязательно. Вопрос будет показан на страницах товаров этой категории', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='faq',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Необязательно. Вопрос будет показан на страницах товаров этой подкатегории', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
    ]
