# Generated by Django 5.2.8 on 2026-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.yandex.ru', help_text='Например: smtp.yandex.ru, smtp.gmail.com', max_length=255, verbose_name='SMTP сервер')),
                ('email_port', models.PositiveIntegerField(default=465, help_text='Обычно 465 для SSL, 587 для TLS', verbose_name='Порт SMTP')),
                ('email_use_ssl', models.BooleanField(default=True, help_text='Включить SSL-шифрование', verbose_name='Использовать SSL')),
                ('email_use_tls', models.BooleanField(default=False, help_text='Включить TLS-шифрование', verbose_name='Использовать TLS')),
                ('email_host_user', models.CharField(default='', help_text='Полный email адрес (например: shop@yandex.ru)', max_length=255, verbose_name='Email отправителя')),
                ('email_host_password', models.CharField(default='', help_text='Пароль приложения (не пароль от почты!)', max_length=255, verbose_name='Пароль приложения')),
                ('default_from_email', models.CharField(blank=True, default='', help_text='Если пусто, используется Email отправителя', max_length=255, verbose_name='Email "От кого"')),
                ('email_subject_prefix', models.CharField(default='[Яблони и Груши]', help_text='Префикс в теме всех писем', max_length=100, verbose_name='Префикс темы письма')),
                ('email_enabled', models.BooleanField(default=True, help_text='Отключите для тестирования без реальной отправки писем', verbose_name='Включить отправку email')),
            ],
            options={
                'verbose_name': 'Настройки email',
                'verbose_name_plural': 'Настройки email',
            },
        ),
    ]
