# Generated by Django 5.2.8 on 2026-02-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='enable_autumn_button',
            field=models.BooleanField(default=True, help_text='Включить/выключить отображение кнопки "Заказать на осень" на страницах товаров', verbose_name='Показывать кнопку "Заказать на осень"'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='enable_spring_button',
            field=models.BooleanField(default=True, help_text='Включить/выключить отображение кнопки "Заказать на весну" на страницах товаров', verbose_name='Показывать кнопку "Заказать на весну"'),
        ),
    ]
