# Generated by Django 5.2.8 on 2026-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailsettings_enable_autumn_button_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_spring_button', models.BooleanField(default=True, help_text='Включить/выключить отображение кнопки "Заказать на весну" на страницах товаров', verbose_name='Показывать кнопку "Заказать на весну"')),
                ('enable_autumn_button', models.BooleanField(default=True, help_text='Включить/выключить отображение кнопки "Заказать на осень" на страницах товаров', verbose_name='Показывать кнопку "Заказать на осень"')),
            ],
            options={
                'verbose_name': 'Настройки кнопок заказа',
                'verbose_name_plural': 'Настройки кнопок заказа',
            },
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='enable_autumn_button',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='enable_spring_button',
        ),
    ]
