# Generated by Django 5.2.8 on 2026-02-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_buttonsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_image', models.ImageField(blank=True, help_text='Изображение, которое отображается в правом контейнере главной страницы', null=True, upload_to='home/', verbose_name='Изображение на главной странице')),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
            },
        ),
        migrations.DeleteModel(
            name='ButtonSettings',
        ),
    ]
