# Generated by Django 5.2.8 on 2026-02-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailsettings_order_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInstructionsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_instructions', models.TextField(blank=True, default='Заказ принят, ожидает оплаты. Все саженцы в наличии, замена сортов без согласования не производится.\n\nОплата на карту СберБанк xxxx xxx xxxxx xxxx на имя Андрей Александрович М.\n\nОбязательно сообщите мне о внесенной оплате на электронную почту (нажав «Ответить» на это письмо). Без этого сообщения я не смогу опознать ваш платеж и приступить к сборке. Срок оплаты заказа - 3 дня.', help_text='Инструкции, которые будут показаны в email уведомлении о заказе. Поддерживает HTML.', verbose_name='Инструкции для заказов')),
            ],
            options={
                'verbose_name': 'Настройки инструкций заказов',
                'verbose_name_plural': 'Настройки инструкций заказов',
            },
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='order_instructions',
        ),
    ]
