# Generated by Django 5.2.8 on 2026-02-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderinstructionssettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinstructionssettings',
            options={'verbose_name': 'Email письмо', 'verbose_name_plural': 'Email письма'},
        ),
    ]
