"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/ 
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import logging

load_dotenv()

# настройки PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pjiup5^^4*96p7x89o963p^^9*w5k!y*i9po9yj@n=2nrmp=2v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# приложения
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'multiupload',
    'core.apps.CoreConfig',
    'blog',
    'catalog.apps.CatalogConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Настройки загрузки медиафайлов
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# русский язык
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'

# настройки для статических файлов
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # os.path.join(BASE_DIR, 'templates')  # Раскомментируйте, если нужно добавить директорию с шаблонами
]

# настройки корзины
CART_SESSION_ID = 'cart'

# Настройки заказов
ORDER_STATUS_CHOICES = (
    ('new', 'Новый заказ'),
    ('in_progress', 'В обработке'),
    ('shipped', 'Отправлен'),
    ('completed', 'Завершен'),
    ('cancelled', 'Отменен'),
)

# Настройки электронной почты сайта
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'  # Yandex SMTP-сервер
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # email из .env
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # пароль приложения из .env

# Используем DEFAULT_FROM_EMAIL из .env или EMAIL_HOST_USER как fallback
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Логирование
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
}

# Пароль приложения — это специальный пароль, который нужно создать в 
# настройках вашего почтового аккаунта Yandex. Вот как это сделать:
# Войдите в свой аккаунт Yandex
# Перейдите в Настройки → Пароли и безопасность → Пароли приложений
# Нажмите Создать пароль
# Введите название приложения, например, "Django Shop"
# Нажмите Создать
# Скопируйте сгенерированный пароль (он покажется только один раз!)
# После этого:
# Вставьте этот пароль в EMAIL_HOST_PASSWORD
# В EMAIL_HOST_USER укажите ваш полный email (например, mymail@yandex.ru)
# В DEFAULT_FROM_EMAIL укажите тот же email
# Важно: Никогда не используйте пароль от почты 
# напрямую — только сгенерированный пароль приложения!

# Настройки аутентификации
LOGIN_REDIRECT_URL = 'home'  # Куда перенаправлять пользователя после входа
LOGOUT_REDIRECT_URL = 'home'  # Куда перенаправлять пользователя после выхода
LOGIN_URL = 'login'  # URL для входа (используется декоратором @login_required)