# Generated by Django 5.2.8 on 2025-11-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_featured_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы показать этот товар в разделе Хиты продаж', verbose_name='Хит продаж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Основное изображение'),
        ),
    ]
