# Generated by Django 5.2.8 on 2025-12-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_is_featured_alter_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы показать этот товар в разделе Новинки', verbose_name='Новинка'),
        ),
    ]
