# Generated by Django 5.2.8 on 2026-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_autumn_button',
            field=models.BooleanField(default=True, help_text='Включить/выключить отображение кнопки "Заказать на осень" на странице этого товара', verbose_name='Показывать кнопку "Заказать на осень"'),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_spring_button',
            field=models.BooleanField(default=True, help_text='Включить/выключить отображение кнопки "Заказать на весну" на странице этого товара', verbose_name='Показывать кнопку "Заказать на весну"'),
        ),
    ]
