# Generated by Django 5.2.8 on 2026-02-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_enable_autumn_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button1_text',
            field=models.CharField(blank=True, default='СОДЕРЖАНИЕ', max_length=100, verbose_name='Текст кнопки 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='button1_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Ссылка кнопки 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='button2_text',
            field=models.CharField(blank=True, default='Характеристика сорта', max_length=100, verbose_name='Текст кнопки 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='button2_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Ссылка кнопки 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='button3_text',
            field=models.CharField(blank=True, default='Правила выращивания', max_length=100, verbose_name='Текст кнопки 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='button3_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Ссылка кнопки 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='button4_text',
            field=models.CharField(blank=True, default='Подготовка к зиме', max_length=100, verbose_name='Текст кнопки 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='button4_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Ссылка кнопки 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='button5_text',
            field=models.CharField(blank=True, default='Болезни и вредители', max_length=100, verbose_name='Текст кнопки 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='button5_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Ссылка кнопки 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='button6_text',
            field=models.CharField(blank=True, default='Сбор урожая', max_length=100, verbose_name='Текст кнопки 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='button6_url',
            field=models.CharField(blank=True, default='#', max_length=200, verbose_name='Ссылка кнопки 6'),
        ),
    ]
