# Generated by Django 5.2.8 on 2026-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_button1_text_product_button1_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='button1_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button2_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button3_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button4_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button5_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button6_url',
        ),
        migrations.AddField(
            model_name='product',
            name='button1_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='button2_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='button3_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='button4_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='button5_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='button6_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 6'),
        ),
    ]
