# Generated by Django 5.2.8 on 2026-02-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_product_button1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button10_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 10'),
        ),
        migrations.AddField(
            model_name='product',
            name='button10_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки 10'),
        ),
        migrations.AddField(
            model_name='product',
            name='button7_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='button7_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='button8_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='button8_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='button9_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 9'),
        ),
        migrations.AddField(
            model_name='product',
            name='button9_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки 9'),
        ),
    ]
