# Generated by Django 5.2.8 on 2026-02-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_button10_content_product_button10_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.subcategory', verbose_name='Подкатегории'),
        ),
    ]
