# Generated by Django 6.0.2 on 2026-09-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_product_subcategory_product_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='button1_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button1_text',
        ),
    ]
