# Generated by Django 6.0.2 on 2026-09-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_button1_content_product_button1_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='button1_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button1_text',
        ),
    ]
