# Generated by Django 6.0.2 on 2026-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_product_button1_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button1_content',
            field=models.TextField(blank=True, verbose_name='Содержимое кнопки 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='button1_text',
            field=models.CharField(blank=True, default='СОДЕРЖАНИЕ', max_length=100, verbose_name='Текст кнопки 1'),
        ),
    ]
