# Generated by Django 6.0.2 on 2026-09-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_button1_content_product_button1_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='button10_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button10_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button1_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button1_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button2_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button2_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button3_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button3_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button4_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button4_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button5_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button5_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button6_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button6_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button7_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button7_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button8_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button8_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button9_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='button9_text',
        ),
    ]
