# Generated by Django 6.0.2 on 2026-09-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_product_button10_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Если оставить пустым — сформируется автоматически из названия и описания товара', verbose_name='SEO Description (описание для поисковиков)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым — будет использовано название товара', max_length=200, verbose_name='SEO Title (заголовок для поисковиков)'),
        ),
    ]
