# Generated by Django 5.2.8 on 2025-11-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_is_featured_cart_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='main_image',
        ),
    ]
