# Generated by Django 5.2.8 on 2026-01-16 09:36

import django.core.validators
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Формат: +7 (XXX) XXX-XX-XX или 8XXXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный российский телефонный номер в формате: +7 (XXX) XXX-XX-XX или 8XXXXXXXXXX', regex='^(\\+7|8)?[\\s\\-]?\\(?[0-9]{3}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$'), orders.models.validate_phone], verbose_name='Телефон'),
        ),
    ]
