# Generated by Django 5.2.8 on 2026-01-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страна, край, район'),
        ),
    ]
