# Generated by Django 5.2.8 on 2026-01-29 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.yandex.ru', max_length=255, verbose_name='SMTP сервер')),
                ('email_port', models.IntegerField(default=465, verbose_name='Порт')),
                ('email_use_ssl', models.BooleanField(default=True, verbose_name='Использовать SSL')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='Использовать TLS')),
                ('email_host_user', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email отправителя')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='Пароль приложения')),
                ('default_from_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активные настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки Email',
                'verbose_name_plural': 'Настройки Email',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_email_settings')],
            },
        ),
    ]
