# Generated by Django 5.2.8 on 2026-01-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host_password',
            field=models.CharField(max_length=500, verbose_name='Пароль приложения'),
        ),
    ]
