# Generated by Django 5.2.8 on 2026-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_emailsettings_email_host_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
    ]
