# Generated by Django 5.2.8 on 2026-02-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_emailsettings_order_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_needed',
            field=models.BooleanField(default=False, verbose_name='Нужна доставка'),
        ),
    ]
