# Generated by Django 5.2.8 on 2026-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_needed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.yandex.ru', max_length=255, verbose_name='SMTP хост')),
                ('email_port', models.PositiveIntegerField(default=465, verbose_name='SMTP порт')),
                ('email_use_ssl', models.BooleanField(default=True, verbose_name='Использовать SSL')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='Использовать TLS')),
                ('email_host_user', models.EmailField(default='tatarhyonok1@yandex.ru', max_length=254, verbose_name='Email для отправки')),
                ('email_host_password', models.CharField(default='', max_length=255, verbose_name='Пароль приложения')),
                ('default_from_email', models.EmailField(default='tatarhyonok1@yandex.ru', max_length=254, verbose_name='Email отправителя')),
            ],
            options={
                'verbose_name': 'Настройки Email',
                'verbose_name_plural': 'Настройки Email',
            },
        ),
    ]
