# Generated by Django 5.2.8 on 2026-02-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_emailsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
        migrations.AddField(
            model_name='order',
            name='privacy_consent',
            field=models.BooleanField(default=False, help_text='Пользователь дал согласие на обработку персональных данных', verbose_name='Согласие на обработку Персональных данных'),
        ),
    ]
