# Generated by Django 5.2.8 on 2026-02-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_delete_emailsettings_order_privacy_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='privacy_consent',
        ),
    ]
