# Generated by Django 5.2.8 on 2026-02-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_privacy_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='season',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сезон'),
        ),
    ]
